name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write  # Required to push to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake.svg
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      # Debugging: List files in dist directory
      - name: List files in dist directory
        run: ls -al dist/

      # Check if snake.svg is generated
      - name: Check the content of snake.svg
        run: |
          if [ -f dist/snake.svg ]; then
            echo "snake.svg generated successfully."
            cat dist/snake.svg
          else
            echo "snake.svg not found."
            exit 1
          fi

      # Push snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
